### ISSUE TITLE
some domains miss the dac_override capability

### ISSUE THREAD

**Issue by milosmalik** [fedora-selinux/selinux-policy#200]
Reboot of my Fedora26 VM (with fc27 selinux-policy and fc27 SELinux user-space) revealed that following rules are missing:
allow NetworkManager_t self:capability dac_override;
allow cupsd_t self:capability dac_override;
allow systemd_logind_t self:capability dac_override;
allow systemd_networkd_t self:capability dac_override;

$ rpm -qa selinux\*
selinux-policy-3.13.1-277.fc27.no_dac_override.100.noarch
selinux-policy-mls-3.13.1-277.fc27.no_dac_override.100.noarch
selinux-policy-devel-3.13.1-277.fc27.no_dac_override.100.noarch
selinux-policy-targeted-3.13.1-277.fc27.no_dac_override.100.noarch
selinux-policy-minimum-3.13.1-277.fc27.no_dac_override.100.noarch
selinux-policy-sandbox-3.13.1-277.fc27.no_dac_override.100.noarch
selinux-policy-doc-3.13.1-277.fc27.no_dac_override.100.noarch
$

**Comment by milosmalik** [comment]
----
type=AVC msg=audit(08/31/2017 17:35:54.401:358) : avc:  denied  { dac_override } for  pid=580 comm=systemd-logind capability=dac_override  scontext=system_u:system_r:systemd_logind_t:s0 tcontext=system_u:system_r:systemd_logind_t:s0 tclass=capability permissive=1 
----
type=AVC msg=audit(08/31/2017 17:36:12.509:131) : avc:  denied  { dac_override } for  pid=597 comm=systemd-network capability=dac_override  scontext=system_u:system_r:systemd_networkd_t:s0 tcontext=system_u:system_r:systemd_networkd_t:s0 tclass=capability permissive=1 
----
type=AVC msg=audit(08/31/2017 17:36:12.572:133) : avc:  denied  { dac_override } for  pid=598 comm=NetworkManager capability=dac_override  scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:system_r:NetworkManager_t:s0 tclass=capability permissive=1 
----
type=AVC msg=audit(08/31/2017 17:36:12.770:137) : avc:  denied  { dac_override } for  pid=613 comm=cupsd capability=dac_override  scontext=system_u:system_r:cupsd_t:s0-s0:c0.c1023 tcontext=system_u:system_r:cupsd_t:s0-s0:c0.c1023 tclass=capability permissive=1 
----

**Comment by milosmalik** [comment]
----
type=PROCTITLE msg=audit(08/31/2017 18:17:53.480:74) : proctitle=/usr/bin/rpcbind -w -f 
type=SYSCALL msg=audit(08/31/2017 18:17:53.480:74) : arch=x86_64 syscall=open success=yes exit=8 a0=0x565163258e29 a1=O_RDONLY|O_CREAT a2=0444 a3=0x19 items=0 ppid=1 pid=360 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=rpcbind exe=/usr/bin/rpcbind subj=system_u:system_r:rpcbind_t:s0 key=(null) 
type=AVC msg=audit(08/31/2017 18:17:53.480:74) : avc:  denied  { dac_override } for  pid=360 comm=rpcbind capability=dac_override  scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:system_r:rpcbind_t:s0 tclass=capability permissive=1 
----

**Comment by wrabcak** [comment]
All AVCs fixed in this build:
https://copr.fedorainfracloud.org/coprs/lvrabec/selinux-policy-dac/build/597056/

Thanks for help!

**Comment by milosmalik** [comment]
After upgrading selinux-policy packages to 3.13.1-277.fc27.no_dac_override.101 following rules are  still missing:
allow cupsd_t self:capability dac_override;
allow rpcbind_t self:capability dac_override;

**Comment by bachradsusi** [comment]
`avc:  denied  { dac_override } for  pid=6710 comm="unbound-anchor" capability=1  scontext=system_u:system_r:named_t:s0 tcontext=system_u:system_r:named_t:s0 tclass=capability permissive=1`

**Comment by wrabcak** [comment]
Thanks @bachradsusi , your AVC will be fixed in following build: 
https://copr.fedorainfracloud.org/coprs/lvrabec/selinux-policy-dac/build/597969/

**Comment by wrabcak** [comment]
We have new build: 
https://copr.fedorainfracloud.org/coprs/lvrabec/selinux-policy-dac/build/600728/

**Comment by bachradsusi** [comment]
type=AVC msg=audit(1505202252.85:230): avc:  denied  { dac_override } for  pid=1669 comm="chronyc" capability=1  scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:chronyd_t:s0 tclass=capability permissive=1
    type=SYSCALL msg=audit(1505202252.85:230): arch=x86_64 syscall=bind success=yes exit=0 a0=3 a1=7ffefa957790 a2=6e a3=0 items=2 ppid=1665 pid=1669 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm=chronyc exe=/usr/bin/chronyc subj=system_u:system_r:chronyd_t:s0 key=(null)
    type=CWD msg=audit(1505202252.85:230): cwd=/
    type=PATH msg=audit(1505202252.85:230): item=0 name=/var/run/chrony/ inode=22981 dev=00:17 mode=040750 ouid=996 ogid=992 rdev=00:00 obj=system_u:object_r:chronyd_var_run_t:s0 nametype=PARENT cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0

**Comment by wrabcak** [comment]
https://copr.fedorainfracloud.org/coprs/lvrabec/selinux-policy-dac/build/601278/

**Comment by bachradsusi** [comment]
type=AVC msg=audit(1505229556.533:1131): avc:  denied  { dac_override } for  pid=32462 comm="sudo" capability=1  scontext=staff_u:staff_r:staff_sudo_t:s0-s0:c0.c1023 tcontext=staff_u:staff_r:staff_sudo_t:s0-s0:c0.c1023 tclass=capability permissive=0
    type=SYSCALL msg=audit(1505229556.533:1131): arch=x86_64 syscall=openat success=no exit=EACCES a0=ffffffffffffff9c a1=55d1ab3e5394 a2=902 a3=0 items=1 ppid=32461 pid=32462 auid=13558 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts12 ses=2 comm=sudo exe=/usr/bin/sudo subj=staff_u:staff_r:staff_sudo_t:s0-s0:c0.c1023 key=(null)
    type=CWD msg=audit(1505229556.533:1131): cwd=/home/plautrba
    type=PATH msg=audit(1505229556.533:1131): item=0 name=/dev/pts/12 inode=15 dev=00:16 mode=020620 ouid=13558 ogid=5 rdev=88:0c obj=staff_u:object_r:user_devpts_t:s0 nametype=NORMAL cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0

**Comment by bachradsusi** [comment]
type=AVC msg=audit(1505240680.722:1180): avc:  denied  { dac_override } for  pid=11684 comm="systemd-udevd" capability=1  scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tclass=capability permissive=0
    type=SYSCALL msg=audit(1505240680.722:1180): arch=x86_64 syscall=openat success=no exit=EACCES a0=ffffffffffffff9c a1=7fff49342c70 a2=80141 a3=124 items=2 ppid=983 pid=11684 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm=systemd-udevd exe=/usr/lib/systemd/systemd-udevd subj=system_u:system_r:udev_t:s0-s0:c0.c1023 key=(null)
    type=CWD msg=audit(1505240680.722:1180): cwd=/
    type=PATH msg=audit(1505240680.722:1180): item=0 name=/run/udev/tags/systemd/ inode=16128 dev=00:17 mode=040755 ouid=0 ogid=0 rdev=00:00 obj=system_u:object_r:udev_var_run_t:s0 nametype=PARENT cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0
    type=PATH msg=audit(1505240680.722:1180): item=1 name=/run/udev/tags/systemd/+backlight:intel_backlight inode=18700 dev=00:17 mode=0100444 ouid=0 ogid=0 rdev=00:00 obj=system_u:object_r:udev_var_run_t:s0 nametype=NORMAL cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0

**Comment by wrabcak** [comment]
Thanks @bachradsusi  for AVCs here is build with fixes:
https://copr.fedorainfracloud.org/coprs/build/601624/

**Comment by wrabcak** [comment]
Closing this, we have  this change in Rawhide. 

@bachradsusi, 
Thanks for help.
